import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { InvoiceBundle } from "@/types/billing";
import { formatCurrency } from "./money";

export async function generateInvoicePdf(bundle: InvoiceBundle) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const dark = rgb(0.067, 0.071, 0.078);
  const muted = rgb(0.37, 0.39, 0.43);
  let y = 780;

  page.drawText("Apex Performance Club", { x: 48, y, size: 20, font: bold, color: dark });
  page.drawText("Premium Fitness Membership Invoice", { x: 48, y: y - 22, size: 10, font: regular, color: muted });
  page.drawText("INVOICE", { x: 455, y, size: 22, font: bold, color: dark });
  page.drawText(bundle.invoice.invoice_number, { x: 455, y: y - 22, size: 10, font: regular, color: muted });
  y -= 70;

  drawLabelValue(page, regular, bold, "Bill To", bundle.member?.full_name ?? "Member", 48, y);
  drawLabelValue(page, regular, bold, "Member ID", bundle.member?.member_code ?? "-", 300, y);
  y -= 42;
  drawLabelValue(page, regular, bold, "Phone", bundle.member?.phone ?? "-", 48, y);
  drawLabelValue(page, regular, bold, "Email", bundle.member?.email ?? "-", 300, y);
  y -= 56;

  page.drawRectangle({ x: 48, y: y - 8, width: 499, height: 28, color: rgb(0.94, 0.95, 0.92) });
  page.drawText("Description", { x: 60, y, size: 10, font: bold, color: dark });
  page.drawText("Qty", { x: 335, y, size: 10, font: bold, color: dark });
  page.drawText("Amount", { x: 455, y, size: 10, font: bold, color: dark });
  y -= 30;

  for (const item of bundle.items) {
    page.drawText(item.description.slice(0, 54), { x: 60, y, size: 10, font: regular, color: dark });
    page.drawText(String(item.quantity), { x: 335, y, size: 10, font: regular, color: dark });
    page.drawText(formatCurrency(item.total_amount ?? 0, bundle.invoice.currency), { x: 455, y, size: 10, font: regular, color: dark });
    y -= 22;
  }

  y -= 20;
  drawAmountLine(page, regular, "Subtotal", bundle.invoice.subtotal_amount, bundle.invoice.currency, y);
  y -= 20;
  drawAmountLine(page, regular, "Discount", bundle.invoice.discount_amount, bundle.invoice.currency, y);
  y -= 20;
  drawAmountLine(page, regular, "Tax", bundle.invoice.tax_amount, bundle.invoice.currency, y);
  y -= 26;
  drawAmountLine(page, bold, "Total", bundle.invoice.total_amount, bundle.invoice.currency, y);
  y -= 24;
  drawAmountLine(page, bold, "Paid", bundle.invoice.amount_paid, bundle.invoice.currency, y);
  y -= 24;
  drawAmountLine(page, bold, "Due", bundle.invoice.amount_due, bundle.invoice.currency, y);

  page.drawText("Thank you for training with Apex Performance Club.", { x: 48, y: 80, size: 11, font: bold, color: dark });
  page.drawText("This invoice is generated by the Apex Gym Management Platform.", { x: 48, y: 62, size: 9, font: regular, color: muted });

  return pdf.save();
}

function drawLabelValue(
  page: ReturnType<PDFDocument["addPage"]>,
  regular: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  bold: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  label: string,
  value: string,
  x: number,
  y: number
) {
  page.drawText(label, { x, y, size: 9, font: regular, color: rgb(0.37, 0.39, 0.43) });
  page.drawText(value.slice(0, 36), { x, y: y - 17, size: 12, font: bold, color: rgb(0.067, 0.071, 0.078) });
}

function drawAmountLine(
  page: ReturnType<PDFDocument["addPage"]>,
  font: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  label: string,
  amount: number | null,
  currency: string,
  y: number
) {
  page.drawText(label, { x: 360, y, size: 11, font, color: rgb(0.067, 0.071, 0.078) });
  page.drawText(formatCurrency(amount, currency), { x: 455, y, size: 11, font, color: rgb(0.067, 0.071, 0.078) });
}
