import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { formatCurrency } from "./money";

type ReceiptData = {
  receiptNumber: string;
  paymentDate: string;
  memberName: string;
  memberCode: string;
  memberEmail: string;
  description: string;
  amount: number;
  currency: string;
  paymentMethod: string;
  razorpayPaymentId: string;
};

export async function generateReceiptPdf(data: ReceiptData) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const dark = rgb(0.067, 0.071, 0.078);
  const muted = rgb(0.37, 0.39, 0.43);
  const green = rgb(0.13, 0.55, 0.13);
  let y = 780;

  page.drawText("Apex Performance Club", { x: 48, y, size: 20, font: bold, color: dark });
  page.drawText("Payment Receipt", { x: 48, y: y - 22, size: 10, font: regular, color: muted });
  page.drawText("RECEIPT", { x: 455, y, size: 22, font: bold, color: dark });
  page.drawText(data.receiptNumber, { x: 455, y: y - 22, size: 10, font: regular, color: muted });
  y -= 70;

  drawLabelValue(page, regular, bold, "Received From", data.memberName, 48, y);
  drawLabelValue(page, regular, bold, "Member ID", data.memberCode, 300, y);
  y -= 42;
  drawLabelValue(page, regular, bold, "Email", data.memberEmail, 48, y);
  drawLabelValue(page, regular, bold, "Payment Date", data.paymentDate, 300, y);
  y -= 56;

  page.drawRectangle({ x: 48, y: y - 8, width: 499, height: 28, color: rgb(0.94, 0.95, 0.92) });
  page.drawText("Description", { x: 60, y, size: 10, font: bold, color: dark });
  page.drawText("Method", { x: 315, y, size: 10, font: bold, color: dark });
  page.drawText("Amount", { x: 455, y, size: 10, font: bold, color: dark });
  y -= 30;

  page.drawText(data.description.slice(0, 54), { x: 60, y, size: 10, font: regular, color: dark });
  page.drawText(data.paymentMethod, { x: 315, y, size: 10, font: regular, color: dark });
  page.drawText(formatCurrency(data.amount, data.currency), { x: 455, y, size: 10, font: regular, color: dark });
  y -= 80;

  page.drawText("PAID", { x: 455, y, size: 14, font: bold, color: green });
  y -= 30;

  page.drawText(`Razorpay Ref: ${data.razorpayPaymentId}`, { x: 48, y, size: 8, font: regular, color: muted });
  y -= 60;

  page.drawText("Thank you for your payment!", { x: 48, y: 80, size: 11, font: bold, color: dark });
  page.drawText("This receipt is generated by the Apex Gym Management Platform.", { x: 48, y: 62, size: 9, font: regular, color: muted });

  return pdf.save();
}

function drawLabelValue(
  page: ReturnType<PDFDocument["addPage"]>,
  regular: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  bold: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  label: string,
  value: string,
  x: number,
  y: number,
) {
  page.drawText(label, { x, y, size: 9, font: regular, color: rgb(0.37, 0.39, 0.43) });
  page.drawText(value.slice(0, 36), { x, y: y - 17, size: 12, font: bold, color: rgb(0.067, 0.071, 0.078) });
}
