-- Enterprise Backup, Recovery & Disaster Recovery Center
-- Backup catalog, restore sessions, replication, verification, storage tiers, approvals, ransomware, compliance

-- 1. BACKUP CATALOG ENHANCEMENT
alter table public.backup_jobs add column if not exists backup_size_bytes bigint null;
alter table public.backup_jobs add column if not exists compression_ratio numeric null;
alter table public.backup_jobs add column if not exists encryption_status text null default 'aes256' check (encryption_status in ('aes256', 'none', 'customer_key'));
alter table public.backup_jobs add column if not exists verification_status text null default 'pending' check (verification_status in ('pending', 'verified', 'failed', 'in_progress'));
alter table public.backup_jobs add column if not exists storage_tier text null default 'hot' check (storage_tier in ('hot', 'warm', 'cold', 'archive'));
alter table public.backup_jobs add column if not exists region text null;
alter table public.backup_jobs add column if not exists environment text null default 'production' check (environment in ('development', 'staging', 'production', 'dr'));
alter table public.backup_jobs add column if not exists is_immutable boolean not null default false;
alter table public.backup_jobs add column if not exists retention_until timestamptz null;
alter table public.backup_jobs add column if not exists parent_backup_id uuid null references public.backup_jobs(id) on delete set null;

-- 2. RESTORE / RECOVERY SESSIONS
create table if not exists public.recovery_sessions (
  id uuid primary key default gen_random_uuid(),
  session_number integer generated by default as identity,
  recovery_type text not null check (recovery_type in (
    'full_platform', 'infrastructure', 'database', 'storage',
    'tenant', 'multi_tenant', 'franchise_group',
    'branch', 'branch_group',
    'membership_data', 'payment_data', 'invoice_data', 'attendance_data', 'booking_data', 'staff_data'
  )),
  status text not null default 'pending' check (status in (
    'pending', 'scope_selected', 'recovery_point_chosen', 'dependencies_validated',
    'impact_analyzed', 'approved', 'executing', 'validating', 'completed', 'failed', 'cancelled'
  )),
  organization_id uuid null references public.organizations(id) on delete set null,
  branch_id uuid null references public.branches(id) on delete set null,
  selected_backup_id uuid null references public.backup_jobs(id) on delete set null,
  recovery_point timestamptz not null default now(),
  restore_scope jsonb not null default '{}'::jsonb,
  records_affected integer null,
  storage_affected_bytes bigint null,
  estimated_downtime_minutes integer null,
  risk_assessment text null check (risk_assessment in ('low', 'medium', 'high', 'critical')),
  dependencies_validated boolean not null default false,
  impact_analysis jsonb not null default '{}'::jsonb,
  approval_level text null check (approval_level in ('level1_ops', 'level2_admin', 'level3_security', 'level4_executive')),
  approved_by uuid null references auth.users(id) on delete set null,
  approved_at timestamptz null,
  justification text null,
  executed_by uuid null references auth.users(id) on delete set null,
  executed_at timestamptz null,
  validated_at timestamptz null,
  validation_result text null check (validation_result in ('passed', 'failed', 'partial')),
  error_message text null,
  metadata jsonb not null default '{}'::jsonb,
  requested_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists recovery_sessions_status_idx on public.recovery_sessions (status, created_at desc);
create index if not exists recovery_sessions_org_idx on public.recovery_sessions (organization_id, created_at desc);
create index if not exists recovery_sessions_type_idx on public.recovery_sessions (recovery_type, created_at desc);
comment on table public.recovery_sessions is 'Enterprise restore/recovery sessions with full workflow tracking';

-- 3. RECOVERY APPROVAL WORKFLOW
create table if not exists public.recovery_approvals (
  id uuid primary key default gen_random_uuid(),
  recovery_session_id uuid not null references public.recovery_sessions(id) on delete cascade,
  approval_level integer not null check (approval_level between 1 and 4),
  approver_role text not null check (approver_role in ('operations', 'platform_admin', 'security', 'executive')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'escalated')),
  approved_by uuid null references auth.users(id) on delete set null,
  rejected_by uuid null references auth.users(id) on delete set null,
  rejection_reason text null,
  mfa_verified boolean not null default false,
  mfa_method text null,
  ip_address inet null,
  responded_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists recovery_approvals_session_idx on public.recovery_approvals (recovery_session_id, approval_level);
comment on table public.recovery_approvals is 'Multi-level approval workflow for recovery operations';

-- 4. DATA REPLICATION MONITORING
create table if not exists public.backup_replication (
  id uuid primary key default gen_random_uuid(),
  backup_job_id uuid not null references public.backup_jobs(id) on delete cascade,
  source_region text not null,
  target_region text not null,
  replication_type text not null check (replication_type in ('active_passive', 'active_active', 'geo_redundant')),
  status text not null default 'pending' check (status in ('pending', 'syncing', 'synced', 'lagging', 'failed', 'not_configured')),
  replication_lag_seconds integer null,
  bytes_transferred bigint null,
  last_synced_at timestamptz null,
  is_healthy boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists backup_replication_status_idx on public.backup_replication (status, source_region);
create index if not exists backup_replication_backup_idx on public.backup_replication (backup_job_id);
comment on table public.backup_replication is 'Cross-region backup replication monitoring';

-- 5. BACKUP VERIFICATION RESULTS
create table if not exists public.backup_verifications (
  id uuid primary key default gen_random_uuid(),
  backup_job_id uuid not null references public.backup_jobs(id) on delete cascade,
  verification_type text not null check (verification_type in ('completeness', 'file_integrity', 'db_consistency', 'encryption_validity', 'full_recovery_test')),
  status text not null default 'pending' check (status in ('pending', 'running', 'passed', 'failed', 'warning')),
  checksum_match boolean null,
  file_count integer null,
  file_count_matched integer null,
  db_consistency_check text null,
  encryption_key_valid boolean null,
  recovery_test_status text null,
  recovery_test_duration_ms integer null,
  notes text null,
  verified_by uuid null references auth.users(id) on delete set null,
  verified_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists backup_verifications_job_idx on public.backup_verifications (backup_job_id);
create index if not exists backup_verifications_status_idx on public.backup_verifications (status);
comment on table public.backup_verifications is 'Automated backup integrity verification results';

-- 6. BACKUP STORAGE TIER MANAGEMENT
create table if not exists public.backup_storage_tiers (
  id uuid primary key default gen_random_uuid(),
  tier_name text not null unique check (tier_name in ('hot', 'warm', 'cold', 'archive')),
  total_storage_bytes bigint not null default 0,
  used_storage_bytes bigint not null default 0,
  backup_count integer not null default 0,
  dedup_savings_bytes bigint null,
  compression_savings_bytes bigint null,
  monthly_cost_usd numeric null,
  retention_min_days integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.backup_storage_tiers (tier_name, retention_min_days) values
  ('hot', 7), ('warm', 30), ('cold', 90), ('archive', 365)
on conflict (tier_name) do nothing;

comment on table public.backup_storage_tiers is 'Backup storage tier management with capacity tracking';

-- 7. RANSOMWARE PROTECTION / TAMPERING DETECTION
create table if not exists public.backup_security_events (
  id uuid primary key default gen_random_uuid(),
  event_type text not null check (event_type in (
    'mass_deletion', 'encryption_activity', 'backup_tampering', 'suspicious_access',
    'immutable_backup_breach', 'air_gap_violation', 'unauthorized_restore'
  )),
  severity text not null check (severity in ('low', 'medium', 'high', 'critical')),
  description text not null,
  backup_job_id uuid null references public.backup_jobs(id) on delete set null,
  detected_by text not null default 'system' check (detected_by in ('system', 'admin', 'automation', 'security_scan')),
  affected_files integer null,
  is_malicious boolean not null default false,
  mitigation_status text not null default 'open' check (mitigation_status in ('open', 'investigating', 'contained', 'resolved')),
  resolved_at timestamptz null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists backup_security_events_type_idx on public.backup_security_events (event_type, created_at desc);
create index if not exists backup_security_events_severity_idx on public.backup_security_events (severity, mitigation_status);
comment on table public.backup_security_events is 'Ransomware detection and backup tampering monitoring';

-- 8. COMPLIANCE REPORTS
create table if not exists public.backup_compliance_reports (
  id uuid primary key default gen_random_uuid(),
  report_type text not null check (report_type in ('backup_compliance', 'recovery_testing', 'dr_readiness', 'audit', 'gdpr', 'soc2', 'hipaa', 'pci')),
  title text not null,
  status text not null default 'generating' check (status in ('generating', 'completed', 'failed')),
  period_start date not null,
  period_end date not null,
  report_data jsonb not null default '{}'::jsonb,
  file_url text null,
  generated_by uuid null references auth.users(id) on delete set null,
  generated_at timestamptz null,
  created_at timestamptz not null default now()
);

comment on table public.backup_compliance_reports is 'Automated backup compliance reporting (GDPR, SOC 2, ISO 27001)';

-- 9. BACKUP SCHEDULES
create table if not exists public.backup_schedules (
  id uuid primary key default gen_random_uuid(),
  schedule_name text not null,
  backup_type text not null check (backup_type in ('database', 'files', 'configuration', 'full')),
  scope text not null default 'platform' check (scope in ('platform', 'tenant', 'branch')),
  frequency text not null check (frequency in ('hourly', 'daily', 'weekly', 'monthly', 'custom_cron')),
  cron_expression text null,
  retention_days integer not null default 30,
  storage_tier text not null default 'hot' check (storage_tier in ('hot', 'warm', 'cold', 'archive')),
  is_active boolean not null default true,
  smart_scheduling boolean not null default false,
  preferred_window_start text null,
  preferred_window_end text null,
  last_run_at timestamptz null,
  next_run_at timestamptz null,
  organization_id uuid null references public.organizations(id) on delete cascade,
  branch_id uuid null references public.branches(id) on delete set null,
  created_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists backup_schedules_active_idx on public.backup_schedules (is_active, next_run_at);
comment on table public.backup_schedules is 'Automated backup scheduling with smart scheduling support';

-- 10. POINT-IN-TIME RECOVERY POINTS
create table if not exists public.backup_pitr_points (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid null references public.organizations(id) on delete cascade,
  resource_type text not null check (resource_type in ('database', 'storage', 'configuration', 'tenant_data')),
  recovery_timestamp timestamptz not null,
  granularity text not null check (granularity in ('exact_timestamp', 'minute', 'hour', 'daily', 'weekly')),
  is_available boolean not null default true,
  backup_job_id uuid null references public.backup_jobs(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists backup_pitr_org_idx on public.backup_pitr_points (organization_id, recovery_timestamp desc);
create index if not exists backup_pitr_resource_idx on public.backup_pitr_points (resource_type, recovery_timestamp desc);

-- 11. SEED INITIAL SCHEDULES
insert into public.backup_schedules (schedule_name, backup_type, scope, frequency, retention_days, is_active)
values
  ('Daily Database Backup', 'database', 'platform', 'daily', 30, true),
  ('Weekly Full Backup', 'full', 'platform', 'weekly', 90, true),
  ('Configuration Backup', 'configuration', 'platform', 'daily', 90, true),
  ('Monthly Archive', 'full', 'platform', 'monthly', 365, true)
on conflict (id) do nothing;

-- SEED STORAGE TIERS
insert into public.backup_storage_tiers (tier_name, total_storage_bytes, used_storage_bytes, backup_count, dedup_savings_bytes, compression_savings_bytes, retention_min_days, is_active)
values
  ('hot', 1099511627776, 214748364800, 120, 42949672960, 85899345920, 7, true),
  ('warm', 5497558138880, 858993459200, 360, 171798691840, 343597383680, 30, true),
  ('cold', 21990232555520, 1717986918400, 180, 343597383680, 687194767360, 90, true),
  ('archive', 43980465111040, 4294967296000, 52, 858993459200, 1717986918400, 365, true)
on conflict (tier_name) do update set
  total_storage_bytes = excluded.total_storage_bytes,
  used_storage_bytes = excluded.used_storage_bytes,
  backup_count = excluded.backup_count;

-- RLS POLICIES
alter table public.recovery_sessions enable row level security;
alter table public.recovery_approvals enable row level security;
alter table public.backup_replication enable row level security;
alter table public.backup_verifications enable row level security;
alter table public.backup_storage_tiers enable row level security;
alter table public.backup_security_events enable row level security;
alter table public.backup_compliance_reports enable row level security;
alter table public.backup_schedules enable row level security;
alter table public.backup_pitr_points enable row level security;

-- Super Admin full access, authenticated read access
do $$
declare
  tables text[] := array[
    'recovery_sessions', 'recovery_approvals', 'backup_replication',
    'backup_verifications', 'backup_storage_tiers', 'backup_security_events',
    'backup_compliance_reports', 'backup_schedules', 'backup_pitr_points'
  ];
  t text;
begin
  foreach t in array tables loop
    execute format('
      create policy "%s_super_admin" on %I for all to authenticated
      using (public.is_super_admin()) with check (public.is_super_admin());
    ', t, t);
    execute format('
      create policy "%s_read" on %I for select to authenticated using (true);
    ', t, t);
  end loop;
end $$;

grant select on all tables in schema public to authenticated;
grant insert, update on public.recovery_sessions to authenticated;
grant insert, update on public.recovery_approvals to authenticated;
grant insert, update on public.backup_replication to authenticated;
grant insert, update on public.backup_verifications to authenticated;
grant insert, update on public.backup_schedules to authenticated;
grant insert on public.backup_security_events to authenticated;
