-- Enterprise Observability & Monitoring Center
-- Incident management, service registry, queue/cron monitoring, on-call, status page, error tracking

-- 1. SERVICE REGISTRY
create table if not exists public.observability_services (
  id uuid primary key default gen_random_uuid(),
  service_name text not null unique,
  service_version text not null default '1.0.0',
  environment text not null default 'production' check (environment in ('development', 'staging', 'production', 'dr')),
  service_type text not null check (service_type in ('api', 'web', 'worker', 'database', 'cache', 'queue', 'storage', 'ai', 'auth', 'payment', 'email', 'sms', 'notification')),
  status text not null default 'unknown' check (status in ('healthy', 'degraded', 'down', 'maintenance', 'unknown')),
  description text null,
  owner_team text null,
  owner_email text null,
  dependencies jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  last_health_check_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists obs_services_type_idx on public.observability_services (service_type);
create index if not exists obs_services_status_idx on public.observability_services (status);
comment on table public.observability_services is 'Service registry for microservice architecture monitoring';

-- 2. SERVICE HEALTH SNAPSHOTS (time-series)
create table if not exists public.observability_service_health (
  id uuid primary key default gen_random_uuid(),
  service_id uuid not null references public.observability_services(id) on delete cascade,
  status text not null check (status in ('healthy', 'degraded', 'down', 'unknown')),
  response_time_ms integer null,
  error_rate numeric null,
  throughput numeric null,
  request_count integer null default 0,
  cpu_usage numeric null,
  memory_usage numeric null,
  message text null,
  checked_at timestamptz not null default now()
);

create index if not exists obs_health_service_time_idx on public.observability_service_health (service_id, checked_at desc);
comment on table public.observability_service_health is 'Time-series health snapshots for each service';

-- 3. INCIDENT MANAGEMENT (Full lifecycle)
create table if not exists public.observability_incidents (
  id uuid primary key default gen_random_uuid(),
  incident_number integer generated by default as identity,
  title text not null,
  description text not null,
  severity text not null check (severity in ('sev1_critical', 'sev2_high', 'sev3_medium', 'sev4_low')),
  status text not null default 'new' check (status in ('new', 'investigating', 'identified', 'mitigated', 'resolved', 'closed')),
  service_id uuid null references public.observability_services(id) on delete set null,
  affected_services jsonb not null default '[]'::jsonb,
  affected_tenants jsonb not null default '[]'::jsonb,
  root_cause text null,
  impact_analysis text null,
  resolution_steps text null,
  timeline_events jsonb not null default '[]'::jsonb,
  owner_id uuid null references auth.users(id) on delete set null,
  severity_level integer not null default 4 check (severity_level between 1 and 4),
  detected_at timestamptz not null default now(),
  identified_at timestamptz null,
  mitigated_at timestamptz null,
  resolved_at timestamptz null,
  closed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists obs_incidents_severity_idx on public.observability_incidents (severity, status);
create index if not exists obs_incidents_status_idx on public.observability_incidents (status, created_at desc);
create index if not exists obs_incidents_service_idx on public.observability_incidents (service_id, created_at desc);
create index if not exists obs_incidents_detected_idx on public.observability_incidents (detected_at desc);
comment on table public.observability_incidents is 'Full incident lifecycle management (SEV-1 to SEV-4)';

-- 4. INCIDENT TIMELINE EVENTS
create table if not exists public.observability_incident_events (
  id uuid primary key default gen_random_uuid(),
  incident_id uuid not null references public.observability_incidents(id) on delete cascade,
  event_type text not null check (event_type in (
    'alert_created', 'service_degraded', 'service_down', 'deployment', 'infrastructure_change',
    'db_failure', 'api_failure', 'manual_action', 'recovery', 'status_change',
    'note_added', 'owner_assigned', 'root_cause_identified', 'mitigation_applied', 'resolved'
  )),
  description text not null,
  severity text null check (severity in ('info', 'warning', 'critical')),
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists obs_incident_events_incident_idx on public.observability_incident_events (incident_id, created_at);
comment on table public.observability_incident_events is 'Granular timeline events for incident correlation';

-- 5. BACKGROUND QUEUE MONITORING
create table if not exists public.observability_queues (
  id uuid primary key default gen_random_uuid(),
  queue_name text not null unique,
  queue_type text not null check (queue_type in ('email', 'sms', 'whatsapp', 'billing', 'analytics', 'notification', 'ai', 'sync', 'report', 'other')),
  current_depth integer not null default 0,
  processing_rate numeric null,
  retry_count integer not null default 0,
  failure_count integer not null default 0,
  success_count integer not null default 0,
  avg_processing_time_ms integer null,
  last_processed_at timestamptz null,
  status text not null default 'active' check (status in ('active', 'degraded', 'backed_up', 'failed', 'paused')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists obs_queues_type_idx on public.observability_queues (queue_type);
comment on table public.observability_queues is 'Background job queue monitoring for all worker types';

-- 6. QUEUE METRICS HISTORY
create table if not exists public.observability_queue_metrics (
  id uuid primary key default gen_random_uuid(),
  queue_id uuid not null references public.observability_queues(id) on delete cascade,
  current_depth integer not null,
  processed_count integer not null default 0,
  failed_count integer not null default 0,
  retry_count integer not null default 0,
  avg_latency_ms integer null,
  recorded_at timestamptz not null default now()
);

create index if not exists obs_queue_metrics_time_idx on public.observability_queue_metrics (queue_id, recorded_at desc);
comment on table public.observability_queue_metrics is 'Time-series queue metrics for trend analysis';

-- 7. CRON / SCHEDULER MONITORING
create table if not exists public.observability_cron_jobs (
  id uuid primary key default gen_random_uuid(),
  job_name text not null unique,
  job_type text not null check (job_type in (
    'membership_renewal', 'billing', 'notification', 'data_sync', 'cleanup',
    'analytics_aggregation', 'ssl_health', 'domain_health', 'trial_expiry',
    'payment_retry', 'revenue_recognition', 'late_fee', 'report_email', 'backup'
  )),
  schedule text not null,
  status text not null default 'active' check (status in ('active', 'paused', 'failed', 'disabled')),
  last_run_at timestamptz null,
  next_run_at timestamptz null,
  last_duration_ms integer null,
  average_duration_ms integer null,
  success_count integer not null default 0,
  failure_count integer not null default 0,
  last_error text null,
  is_overdue boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists obs_cron_status_idx on public.observability_cron_jobs (status, next_run_at);
create index if not exists obs_cron_type_idx on public.observability_cron_jobs (job_type);
comment on table public.observability_cron_jobs is 'Cron job and scheduler monitoring with run tracking';

-- 8. CRON RUN HISTORY
create table if not exists public.observability_cron_runs (
  id uuid primary key default gen_random_uuid(),
  cron_job_id uuid not null references public.observability_cron_jobs(id) on delete cascade,
  status text not null check (status in ('running', 'completed', 'failed', 'skipped', 'delayed')),
  duration_ms integer null,
  error_message text null,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz null
);

create index if not exists obs_cron_runs_job_idx on public.observability_cron_runs (cron_job_id, started_at desc);
create index if not exists obs_cron_runs_status_idx on public.observability_cron_runs (status, started_at desc);

-- 9. ERROR TRACKING
create table if not exists public.observability_errors (
  id uuid primary key default gen_random_uuid(),
  error_type text not null check (error_type in (
    'frontend', 'backend_exception', 'api_failure', 'database_error',
    'third_party', 'ai_error', 'payment_error', 'auth_error', 'validation_error'
  )),
  error_message text not null,
  stack_trace text null,
  severity text not null default 'medium' check (severity in ('low', 'medium', 'high', 'critical')),
  service_name text null,
  endpoint text null,
  method text null,
  status_code integer null,
  user_id uuid null,
  tenant_id uuid null,
  request_id text null,
  correlation_id text null,
  metadata jsonb not null default '{}'::jsonb,
  frequency integer not null default 1,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  is_resolved boolean not null default false,
  resolved_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists obs_errors_type_severity_idx on public.observability_errors (error_type, severity, last_seen_at desc);
create index if not exists obs_errors_service_idx on public.observability_errors (service_name, last_seen_at desc);
create index if not exists obs_errors_frequency_idx on public.observability_errors (frequency desc);
comment on table public.observability_errors is 'Centralized error tracking for all application errors';

-- 10. LOG MANAGEMENT
create table if not exists public.observability_logs (
  id bigserial,
  log_level text not null check (log_level in ('debug', 'info', 'warn', 'error', 'fatal')),
  message text not null,
  service_name text null,
  request_id text null,
  correlation_id text null,
  tenant_id uuid null,
  user_id uuid null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);

-- Create monthly partitions for logs
do $$
declare
  start_date timestamptz := '2026-01-01'::timestamptz;
  end_date timestamptz := '2028-01-01'::timestamptz;
  d timestamptz := start_date;
  partition_name text;
begin
  while d < end_date loop
    partition_name := 'observability_logs_' || to_char(d, 'YYYYMM');
    execute format(
      'create table if not exists public.%I partition of public.observability_logs for values from (%L) to (%L)',
      partition_name, d, d + interval '1 month'
    );
    d := d + interval '1 month';
  end loop;
end $$;

create index if not exists obs_logs_level_idx on public.observability_logs (log_level, created_at desc);
create index if not exists obs_logs_service_idx on public.observability_logs (service_name, created_at desc);
create index if not exists obs_logs_request_idx on public.observability_logs (request_id);
create index if not exists obs_logs_correlation_idx on public.observability_logs (correlation_id);
comment on table public.observability_logs is 'Centralized log management with monthly partitioning';

-- 11. ON-CALL SCHEDULING
create table if not exists public.observability_oncall_schedules (
  id uuid primary key default gen_random_uuid(),
  schedule_name text not null,
  team_name text not null,
  escalation_level integer not null default 1 check (escalation_level between 1 and 4),
  primary_user_id uuid null references auth.users(id) on delete set null,
  backup_user_id uuid null references auth.users(id) on delete set null,
  rotation_type text not null default 'weekly' check (rotation_type in ('daily', 'weekly', 'biweekly', 'monthly')),
  rotation_start_date date not null,
  is_active boolean not null default true,
  notification_channels jsonb not null default '["slack", "sms"]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists obs_oncall_team_idx on public.observability_oncall_schedules (team_name, is_active);
comment on table public.observability_oncall_schedules is 'On-call scheduling with rotation and escalation';

-- 12. STATUS PAGE COMPONENTS
create table if not exists public.observability_status_pages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text null,
  is_public boolean not null default false,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.observability_status_pages is 'Status page configurations (public/private)';

create table if not exists public.observability_status_components (
  id uuid primary key default gen_random_uuid(),
  status_page_id uuid not null references public.observability_status_pages(id) on delete cascade,
  service_id uuid null references public.observability_services(id) on delete set null,
  name text not null,
  status text not null default 'operational' check (status in ('operational', 'degraded', 'partial_outage', 'major_outage', 'maintenance')),
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists obs_status_components_page_idx on public.observability_status_components (status_page_id, display_order);

create table if not exists public.observability_status_updates (
  id uuid primary key default gen_random_uuid(),
  status_page_id uuid not null references public.observability_status_pages(id) on delete cascade,
  title text not null,
  message text not null,
  status text not null check (status in ('investigating', 'identified', 'monitoring', 'resolved')),
  severity text not null check (severity in ('minor', 'major', 'critical')),
  created_at timestamptz not null default now()
);

create index if not exists obs_status_updates_page_idx on public.observability_status_updates (status_page_id, created_at desc);

-- 13. CAPACITY FORECASTING
create table if not exists public.observability_capacity_metrics (
  id uuid primary key default gen_random_uuid(),
  metric_type text not null check (metric_type in (
    'database_size', 'storage_size', 'traffic_volume', 'api_requests',
    'queue_depth', 'active_users', 'bandwidth', 'memory_usage', 'cpu_usage'
  )),
  current_value numeric not null,
  forecast_value_30d numeric null,
  forecast_value_90d numeric null,
  growth_rate numeric null,
  capacity_limit numeric null,
  usage_percent numeric null,
  recorded_at date not null default current_date,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists obs_capacity_metric_date_idx on public.observability_capacity_metrics (metric_type, recorded_at desc);
comment on table public.observability_capacity_metrics is 'Capacity planning metrics with growth forecasting';

-- 14. TENANT MONITORING
create table if not exists public.observability_tenant_health (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  availability_score numeric not null default 100,
  error_count integer not null default 0,
  performance_score numeric null,
  resource_usage_pct numeric null,
  last_incident_at timestamptz null,
  revenue_risk text null check (revenue_risk in ('low', 'medium', 'high', 'critical')),
  health_score numeric not null default 100,
  checked_at timestamptz not null default now()
);

create index if not exists obs_tenant_health_org_idx on public.observability_tenant_health (organization_id, checked_at desc);
create index if not exists obs_tenant_health_score_idx on public.observability_tenant_health (health_score asc);

-- 15. ESCALATION POLICY
create table if not exists public.observability_escalation_policies (
  id uuid primary key default gen_random_uuid(),
  policy_name text not null,
  description text null,
  levels jsonb not null default '[
    {"level": 1, "name": "Operations Team", "timeout_minutes": 15, "notify_channels": ["slack", "sms"]},
    {"level": 2, "name": "Engineering Team", "timeout_minutes": 30, "notify_channels": ["slack", "sms", "phone"]},
    {"level": 3, "name": "Platform Team", "timeout_minutes": 60, "notify_channels": ["slack", "phone"]},
    {"level": 4, "name": "Leadership", "timeout_minutes": 120, "notify_channels": ["phone", "email"]}
  ]'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- RLS POLICIES
alter table public.observability_services enable row level security;
alter table public.observability_service_health enable row level security;
alter table public.observability_incidents enable row level security;
alter table public.observability_incident_events enable row level security;
alter table public.observability_queues enable row level security;
alter table public.observability_queue_metrics enable row level security;
alter table public.observability_cron_jobs enable row level security;
alter table public.observability_cron_runs enable row level security;
alter table public.observability_errors enable row level security;
alter table public.observability_logs enable row level security;
alter table public.observability_oncall_schedules enable row level security;
alter table public.observability_status_pages enable row level security;
alter table public.observability_status_components enable row level security;
alter table public.observability_status_updates enable row level security;
alter table public.observability_capacity_metrics enable row level security;
alter table public.observability_tenant_health enable row level security;
alter table public.observability_escalation_policies enable row level security;

-- SUPER ADMIN has full access; authenticated users read-only
create policy "observability super admin full access"
on public.observability_services for all to authenticated
using (public.is_super_admin())
with check (public.is_super_admin());

create policy "observability read for authenticated"
on public.observability_services for select to authenticated
using (true);

-- Same pattern for all observability tables
do $$
declare
  tables text[] := array[
    'observability_service_health', 'observability_incidents', 'observability_incident_events',
    'observability_queues', 'observability_queue_metrics', 'observability_cron_jobs',
    'observability_cron_runs', 'observability_errors', 'observability_logs',
    'observability_oncall_schedules', 'observability_status_pages', 'observability_status_components',
    'observability_status_updates', 'observability_capacity_metrics', 'observability_tenant_health',
    'observability_escalation_policies'
  ];
  t text;
begin
  foreach t in array tables loop
    execute format('
      create policy "obs_%s_super_admin" on %I for all to authenticated
      using (public.is_super_admin()) with check (public.is_super_admin());
    ', replace(t, 'observability_', ''), t);
    execute format('
      create policy "obs_%s_read" on %I for select to authenticated using (true);
    ', replace(t, 'observability_', ''), t);
  end loop;
end $$;

-- Seed initial services
insert into public.observability_services (service_name, service_type, status, description, owner_team, dependencies)
values
  ('API Gateway', 'api', 'healthy', 'Main REST API gateway for all platform services', 'Platform Team', '[]'),
  ('Web Application', 'web', 'healthy', 'Next.js frontend application', 'Platform Team', '["API Gateway"]'),
  ('Supabase Database', 'database', 'healthy', 'PostgreSQL database via Supabase', 'Platform Team', '[]'),
  ('Redis Cache', 'cache', 'healthy', 'In-memory caching layer', 'Platform Team', '["Supabase Database"]'),
  ('Email Service (Resend)', 'email', 'healthy', 'Transactional email delivery via Resend', 'Platform Team', '["API Gateway"]'),
  ('Payment Gateway (Razorpay)', 'payment', 'healthy', 'Payment processing via Razorpay', 'Finance Team', '["API Gateway"]'),
  ('Background Workers', 'worker', 'healthy', 'Background job processing', 'Platform Team', '["Supabase Database"]'),
  ('AI Service (OpenAI)', 'ai', 'healthy', 'AI-powered features and recommendations', 'AI Team', '["API Gateway"]'),
  ('SMS Service', 'sms', 'healthy', 'SMS notifications and alerts', 'Platform Team', '["API Gateway"]'),
  ('WhatsApp Service', 'notification', 'healthy', 'WhatsApp messaging for members', 'Platform Team', '["API Gateway"]'),
  ('Auth Service (Supabase)', 'auth', 'healthy', 'Authentication and authorization', 'Platform Team', '["Supabase Database"]'),
  ('File Storage', 'storage', 'healthy', 'File and media storage', 'Platform Team', '["Supabase Database"]')
on conflict (service_name) do nothing;

-- Seed queue definitions
insert into public.observability_queues (queue_name, queue_type)
values
  ('email-queue', 'email'),
  ('sms-queue', 'sms'),
  ('whatsapp-queue', 'whatsapp'),
  ('billing-queue', 'billing'),
  ('analytics-queue', 'analytics'),
  ('notification-queue', 'notification'),
  ('ai-queue', 'ai'),
  ('sync-queue', 'sync')
on conflict (queue_name) do nothing;

-- Seed cron jobs
insert into public.observability_cron_jobs (job_name, job_type, schedule)
values
  ('Super Admin Dashboard Summary', 'report_email', '0 9 * * 1'),
  ('Organization Approvals Expire', 'cleanup', '0 2 * * *'),
  ('Domain Health Alerts', 'domain_health', '0 */6 * * *'),
  ('SSL Certificate Check', 'ssl_health', '0 */12 * * *'),
  ('Domain Registration Expiry', 'domain_health', '0 3 * * *'),
  ('Subscription Billing', 'billing', '0 4 * * *'),
  ('Trial Expiry', 'trial_expiry', '0 5 * * *'),
  ('Payment Retry (Dunning)', 'payment_retry', '0 */4 * * *'),
  ('Subscription Renewals', 'notification', '0 6 * * *'),
  ('Revenue Recognition', 'revenue_recognition', '0 7 * * *'),
  ('Late Fee Application', 'late_fee', '0 8 * * *'),
  ('Subscription Usage Snapshots', 'analytics_aggregation', '0 */12 * * *'),
  ('Membership Renewal Reminders', 'membership_renewal', '0 9 * * *')
on conflict (job_name) do nothing;

-- Seed enterprise escalation policy
insert into public.observability_escalation_policies (policy_name, description)
values ('Default Enterprise Escalation', 'Standard 4-level escalation chain for production incidents')
on conflict (id) do nothing;

-- GRANTS
grant usage on schema public to authenticated;
grant select on all tables in schema public to authenticated;
grant insert, update on public.observability_services to authenticated;
grant insert, update on public.observability_incidents to authenticated;
grant insert, update on public.observability_incident_events to authenticated;
grant insert, update on public.observability_queues to authenticated;
grant insert, update on public.observability_cron_jobs to authenticated;
grant insert, update on public.observability_errors to authenticated;
grant insert on public.observability_logs to authenticated;
grant insert, update on public.observability_oncall_schedules to authenticated;
grant insert, update on public.observability_status_pages to authenticated;
grant insert, update on public.observability_status_components to authenticated;
grant insert, update on public.observability_status_updates to authenticated;
